CREATE TABLE Locacao(
Id INT IDENTITY(1,1) PRIMARY KEY,
Nome NVARCHAR(200) NOT NULL,
EmaiL NVARCHAR(150) NOT NULL,
Model NVARCHAR(100) NOT NULL,
Vehicledate INT NOT NULL,
Rentaltime NVARCHAR(50) NOT NULL,
Requestdate DATETIME2 NOT NULL,
Purchasedate DATETIME2 DEFAULT GETDATE() 
)